version: "3.8"
services:
  postgres:
    image: postgres
    ports:
      - 6969:5432
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=my
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
